AlimentacionSantiago/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls')),
]

app/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    # Aqui iran las URLS para accesos a pantallas del proyecto
    path('registro/', registro, name='registro'),
    path('', inicio, name='inicio'),
    path('login/', inicio_sesion, name='iniciar_sesion'),
    path('logout/', cerrar_sesion, name='cerrar_sesion'),
    path('clientes/', ListadoCliente, name='ListadoCliente'),
    path('modificar/<rut>', ModificarCliente, name='ModificarCliente'),
    path('eliminar/<rut>', EliminarCliente, name='EliminarCliente'),
    path('confirmarEliminar/<rut>/',ConfirmarEliminacionCliente, name="Confirmar"),
    path('listaVentas/',listado_ventas, name='listado'),
    path('descarga/resumen-ventas-global/',descarga_ventas, name='descarga'),
]

app/models.py
from django.db import models
from django.core.validators import RegexValidator, MinLengthValidator, MinValueValidator, MaxLengthValidator, MaxValueValidator
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
from django.utils import timezone
# Create your models here.

#Validacion de los campos de usuario
def validar_rut(value):
    error = 'El rut ingresado no es valido. Ingreselo sin puntos ni digito verificador'
    if len(str(value)) < 7 or len(str(value)) > 8:
        raise ValidationError(error)
    
    value2 = str(value)
    
    for c in value2:
        if not c.isdigit():
            raise ValidationError(error)

def validar_nombre(value):
    error = 'Ingrese unicamente letras'
    
    for c in value:
        if not c.isalpha():
            raise ValidationError(error)
    


class Cliente(models.Model):
    rut = models.IntegerField(primary_key=True, validators=[validar_rut])
    
    DIGITO_VERIFICADOR = [
        ("1", "1"),
        ("2", "2"),
        ("3", "3"),
        ("4", "4"),
        ("5", "5"),
        ("6", "6"),
        ("7", "7"),
        ("8", "8"),
        ("9", "9"),
        ("K", "K"),
    ]
    dv = models.TextField(null=False, choices=DIGITO_VERIFICADOR)
    
    nombre = models.CharField(null=False, max_length=20, validators=[validar_nombre])
    apellido = models.CharField(null=False, max_length=20, validators=[validar_nombre])
    usuario = models.OneToOneField(User, on_delete=models.PROTECT)
    correo = models.EmailField(unique=True, null=False)
    
    def __str__(self):
        return str(f'{self.rut}')


def validad_fecha(value):
    if value > timezone.now().date():
        raise ValidationError("La fecha no puede ser una fecha futura.")

class Venta(models.Model):
    id = models.AutoField(primary_key=True)
    fecha = models.DateField(validators=[validad_fecha],unique=True)
    numero_ventas = models.IntegerField(validators=[MinValueValidator(0)])
    costos = models.IntegerField(default=1000,validators=[MinValueValidator(0)])
    ingresos = models.IntegerField(default=0,validators=[MinValueValidator(0)])

    def totalIng(self):
        return self.costos - self.ingresos

    def __str__(self):
        return str(f'{self.fecha}')

app/templates/app/Modificar_Cuenta.html
{% extends 'app/base.html' %}

{% load static %}

{% block css %}
    <link rel="stylesheet" href="{% static 'app/'%}css/login.css">
{% endblock css %}

{% block contenido%}

    <form action="" method="POST">
        {% csrf_token %}
        <section class="form-registro">
            <center>
                {% if user.is_authenticated %}
                <h2> {{ user.username}} </h2>
                {% endif %}
                <h2 color="white">Modificar Cliente</h2>
                <br>
                    <table>
                        {{form.as_table}}
                    </table>
                <input class="boton" type="reset" value="Limpiar">
                <input class="boton" type="submit" value="Modificar">
                {{mensaje}}
                <a href="{% url 'Listado' %}">Volver</a>
            </center>
        </section>
    </form>

{% endblock%}

app/templates/app/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'app/'%}css/base.css">
    {% block css %}
    
    {% endblock css %}
    <title>Document</title>
</head>
<body>
    {% comment %} navbar {% endcomment %}
    <div class="topnav" id="myTopnav">
        <a href="{% url 'inicio' %}" class="active">Inicio</a>
        {% if user.is_authenticated %}
            <a href="{% url 'cerrar_sesion' %}">{{user.username}}: cerrar sesion</a>
        {% else %}
            <a href="{% url 'iniciar_sesion' %}">Iniciar Sesion</a>
        {% endif %}
        {% if perms.app.add_cliente %}
            <a href="{% url 'ListadoCliente' %}">Clientes</a>
            <a href="{% url 'listado' %}">ventas</a>
        {% endif %}
        
        
        <a href="javascript:void(0);" class="icon" onclick="myFunction()"><i class="fa fa-bars"></i></a>
    </div>

    <div class="container">
        {% block contenido %}
        
        {% endblock contenido %}
    </div>
    <!-- footer -->
    <footer>
        <div class="footer">
        <p>Dirijete a cualquiera de nuestras redes sociales</p>
        <a href="#"><img src="{% static 'app/'%}img/pepoclown.gif" width="70px" /></a>
        </div>
    </footer>
</body>
</html>

app/templates/app/confirmacion.html
{% extends 'app/base.html' %}

{% load static %}

{% block css %}
    <link rel="stylesheet" href="{% static 'app/'%}css/confirmacion.css">
{% endblock css %}

{% block contenido %}
    <form action="" method="post">
        {% csrf_token %}
        <section class="form-registro centrado">
            <h1><!-- aqui va el mensaje --> ¿Seguro que quiere eliminar si cuenta? </h1>
            <br>
            <a class="eliminar" href="{% url 'EliminarCliente' cliente %}">Eliminar</a>
            <a class="boton"  onclick="" href="{% url 'ListadoCliente' %}">Cancelar</a>
        </section>
    </form>
{% endblock contenido %}

app/templates/app/index.html
{% extends 'app/base.html' %}

{% load static %}

{% block css %}

{% endblock css %}

{% block contenido %}
    <h1>Hola soy el index</h1>

    {% if user.is_authenticated %}
        <p>Hola {{user.username}}</p>
    {% endif %}
{% endblock contenido %}

app/templates/app/lista_cliente.html
{% extends 'app/base.html' %}

{% load static %}

{% block css %}
    <link rel="stylesheet" href="{% static 'app/'%}css/lista_cliente.css">
{% endblock css %}

{% block contenido%}
    <form action="" method="post">
        <section class="form-registro">
            <h4>Lista de Cuentas</h4>
            <table>
                    <tr>
                        <th >Rut</th>
                        <th >Dv</th>
                        <th >Nombre</th>
                        <th>Apellido</th>
                        <th>Usuario</th>
                        <th>Correo</th>
                    </tr>
                
                    {% for i in Clientes %}
                        <tr>
                            <td>{{i.rut}}</td>
                            <td> {{i.dv}} </td>
                            <td> {{i.nombre}} </td>
                            <td> {{i.apellido}} </td>
                            <td> {{i.usuario}} </td>
                            <td> {{i.correo}} </td>
        
                            <td><a class="Modificar" href="{% url 'ModificarCliente' i.rut %}">Modificar</a></td>
                            <td><a class="eliminar" href="{% url 'Confirmar' i.rut %}">Eliminar</a></td>
                        </tr>
                    {% endfor %}
            </table>
            <a class="boton" href="{% url 'registro' %}">Agregar</a>
        </section>
    </form>
{% endblock%}